# Generated by Django 5.2 on 2025-05-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0005_alter_booking_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_type', models.CharField(choices=[('breakfast', 'Breakfast Service'), ('transport', 'Airport Transfer Service')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('breakfast_count', models.IntegerField(blank=True, help_text='Number of people for breakfast', null=True)),
                ('transport_direction', models.CharField(blank=True, choices=[('to_hotel', 'To Hotel'), ('from_hotel', 'From Hotel')], max_length=20, null=True)),
                ('transport_date', models.DateField(blank=True, null=True)),
                ('transport_time', models.TimeField(blank=True, null=True)),
                ('passenger_count', models.IntegerField(blank=True, help_text='Number of passengers (max 5)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='hotel_booking.booking')),
            ],
            options={
                'verbose_name': 'Booking Add-on',
                'verbose_name_plural': 'Booking Add-ons',
            },
        ),
    ]
