# Generated by Django 5.2 on 2025-05-27 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0006_bookingaddon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('cleaning', 'Room Cleaning'), ('dnd', 'Do Not Disturb')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('cleaning_time_slot', models.CharField(blank=True, choices=[('now', 'Now'), ('after_2pm', 'After 2 PM'), ('tomorrow_morning', 'Tomorrow Morning')], max_length=20, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special cleaning instructions')),
                ('dnd_active', models.BooleanField(default=False, help_text='Is Do Not Disturb currently active')),
                ('dnd_start_time', models.DateTimeField(blank=True, null=True)),
                ('dnd_end_time', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Staff notes')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_services', to='hotel_booking.booking')),
            ],
            options={
                'verbose_name': 'Room Service Request',
                'verbose_name_plural': 'Room Service Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
